data:
  raw:
    file: "../data/raw/de_credit_data_raw.csv"
    # file2: "../data/raw/file2.csv"
  clean:
    file: "../data/clean/de_credit_data_cleaned.csv"
    # file2: "../data/clean/file2_cleaned.csv"  
